-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 00:31:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinepython
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinepython` ;

-- -----------------------------------------------------
-- Schema cinepython
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinepython` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinepython` ;

-- -----------------------------------------------------
-- Table `cinepython`.`salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`salas` (
  `IdSala` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Filas` INT NULL DEFAULT NULL,
  `Butacasporfila` INT NULL DEFAULT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`IdSala`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`peliculas` (
  `IdPelicula` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Director` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Descripcion` VARCHAR(1000) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Genero` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Duracion` FLOAT NOT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`IdPelicula`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`horarios` (
  `Horario` TIME NOT NULL,
  `Precio` DOUBLE(8,2) NULL DEFAULT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`Horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`funciones` (
  `IdFuncion` INT NOT NULL AUTO_INCREMENT,
  `IdSala` INT NOT NULL,
  `IdPelicula` INT NOT NULL,
  `Horario` TIME NOT NULL,
  `Fecha` DATE NOT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`IdFuncion`, `IdSala`, `IdPelicula`, `Horario`, `Fecha`),
  INDEX `IdSala` (`IdSala` ASC) VISIBLE,
  INDEX `IdPelicula` (`IdPelicula` ASC) VISIBLE,
  INDEX `Horario` (`Horario` ASC) VISIBLE,
  CONSTRAINT `funciones_ibfk_1`
    FOREIGN KEY (`IdSala`)
    REFERENCES `cinepython`.`salas` (`IdSala`),
  CONSTRAINT `funciones_ibfk_2`
    FOREIGN KEY (`IdPelicula`)
    REFERENCES `cinepython`.`peliculas` (`IdPelicula`),
  CONSTRAINT `funciones_ibfk_3`
    FOREIGN KEY (`Horario`)
    REFERENCES `cinepython`.`horarios` (`Horario`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`butacas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`butacas` (
  `IdButaca` INT NOT NULL AUTO_INCREMENT,
  `IdFuncion` INT NULL DEFAULT NULL,
  `Fila` INT NULL DEFAULT NULL,
  `Columna` INT NULL DEFAULT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`IdButaca`),
  INDEX `IdFuncion` (`IdFuncion` ASC) VISIBLE,
  CONSTRAINT `butacas_ibfk_1`
    FOREIGN KEY (`IdFuncion`)
    REFERENCES `cinepython`.`funciones` (`IdFuncion`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`usuarios` (
  `IdUsuario` VARCHAR(70) NOT NULL,
  `clave` VARCHAR(10) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Nombre` VARCHAR(60) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Apellido` VARCHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Estado` INT NULL DEFAULT '1',
  `FechaNacimiento` DATE NOT NULL,
  `Celular` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinepython`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinepython`.`reservas` (
  `IdReserva` INT NOT NULL AUTO_INCREMENT,
  `Horario` TIME NOT NULL,
  `IdFuncion` INT NOT NULL,
  `IdSala` INT NOT NULL,
  `IdPelicula` INT NOT NULL,
  `IdUsuario` VARCHAR(70) NOT NULL,
  `Nombre` VARCHAR(60) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `Fecha` DATE NOT NULL,
  `Precio` DOUBLE NULL DEFAULT NULL,
  `Estado` INT NULL DEFAULT '1',
  PRIMARY KEY (`IdReserva`),
  INDEX `IdUsuario` (`IdUsuario` ASC) VISIBLE,
  INDEX `IdFuncion` (`IdFuncion` ASC, `IdSala` ASC, `IdPelicula` ASC, `Horario` ASC, `Fecha` ASC) VISIBLE,
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `cinepython`.`usuarios` (`IdUsuario`),
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`IdFuncion` , `IdSala` , `IdPelicula` , `Horario` , `Fecha`)
    REFERENCES `cinepython`.`funciones` (`IdFuncion` , `IdSala` , `IdPelicula` , `Horario` , `Fecha`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
